tesseract:
    data directory: default
    recognition language: eng
    ocr engine mode: 3

input image processing:
    scale factor: 1
    invert: no
    grayscale: no
    blackwhite: no
    blackwhite threshold: 200

speech:
    speech module: espeak-ng
    language: en
    voice: male1
    punctuation mode: some
    pitch: 10
    rate: 2
    volume: 100

